from fastapi import FastAPI, Request, Form, UploadFile, File
from fastapi.responses import HTMLResponse, StreamingResponse, RedirectResponse
from fastapi.templating import Jinja2Templates
from fastapi.staticfiles import StaticFiles
from starlette.middleware.sessions import SessionMiddleware
from passlib.context import CryptContext
from sqlalchemy import create_engine, text
from sqlalchemy.exc import IntegrityError
import os, secrets, pandas as pd
from io import BytesIO
from pathlib import Path
from datetime import datetime

BASE = Path(__file__).resolve().parent
DATABASE_URL = os.getenv("DATABASE_URL", f"sqlite:///{BASE/'service_usage.db'}")
if DATABASE_URL.startswith("postgres://"):
    DATABASE_URL = DATABASE_URL.replace("postgres://", "postgresql+psycopg://", 1)
elif DATABASE_URL.startswith("postgresql://"):
    DATABASE_URL = DATABASE_URL.replace("postgresql://", "postgresql+psycopg://", 1)

engine_kwargs = {"pool_pre_ping": True, "future": True}
if not DATABASE_URL.startswith("sqlite:"):
    engine_kwargs.update({"pool_size": 5, "max_overflow": 5, "pool_recycle": 1800})
engine = create_engine(DATABASE_URL, **engine_kwargs)
DB_IS_SQLITE = engine.dialect.name == "sqlite"
pwd = CryptContext(schemes=["bcrypt"], deprecated="auto")
ENV = os.getenv("ENVIRONMENT", "development").lower()
SECRET_KEY = os.getenv("SECRET_KEY")
if ENV == "production" and not SECRET_KEY:
    raise RuntimeError("SECRET_KEY must be set in production")
SECRET_KEY = SECRET_KEY or "dev-only-change-me"

app = FastAPI(title="Service Usage Manager V5")
app.add_middleware(
    SessionMiddleware,
    secret_key=SECRET_KEY,
    session_cookie="service_usage_session",
    same_site="lax",
    https_only=(ENV == "production"),
    max_age=8 * 60 * 60,
)
# Ensure the static directory exists even if an incomplete Git checkout omits it.
STATIC_DIR = BASE / "static"
STATIC_DIR.mkdir(parents=True, exist_ok=True)
app.mount("/static", StaticFiles(directory=STATIC_DIR), name="static")
templates = Jinja2Templates(directory=str(BASE / "templates"))

FIELDS = ["province","type","source_ne","source_port","direction","dest_ne","dest_port","rate_type","rate_number","status","service"]


def db():
    return engine.begin()


def init_db():
    if DB_IS_SQLITE:
        user_id = "INTEGER PRIMARY KEY AUTOINCREMENT"
        record_id = "INTEGER PRIMARY KEY AUTOINCREMENT"
        audit_id = "INTEGER PRIMARY KEY AUTOINCREMENT"
    else:
        user_id = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        record_id = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
        audit_id = "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
    with db() as c:
        c.execute(text(f"""CREATE TABLE IF NOT EXISTS users(
            id {user_id},
            username VARCHAR(100) UNIQUE NOT NULL,
            password_hash TEXT NOT NULL,
            role VARCHAR(20) NOT NULL DEFAULT 'user',
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )"""))
        c.execute(text(f"""CREATE TABLE IF NOT EXISTS records(
            id {record_id},
            province VARCHAR(100), type VARCHAR(100), source_ne VARCHAR(255), source_port VARCHAR(255),
            direction VARCHAR(50), dest_ne VARCHAR(255), dest_port VARCHAR(255), rate_type VARCHAR(100),
            rate_number VARCHAR(50), status VARCHAR(50), service VARCHAR(255),
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )"""))
        c.execute(text(f"""CREATE TABLE IF NOT EXISTS audit_logs(
            id {audit_id},
            user_id INTEGER, username VARCHAR(100), action VARCHAR(100) NOT NULL,
            target_type VARCHAR(100), target_id VARCHAR(100), details TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        )"""))
        c.execute(text("CREATE INDEX IF NOT EXISTS idx_records_province ON records(province)"))
        c.execute(text("CREATE INDEX IF NOT EXISTS idx_records_source_ne ON records(source_ne)"))
        c.execute(text("CREATE INDEX IF NOT EXISTS idx_records_dest_ne ON records(dest_ne)"))
        c.execute(text("CREATE INDEX IF NOT EXISTS idx_records_status ON records(status)"))
        c.execute(text("CREATE INDEX IF NOT EXISTS idx_records_service ON records(service)"))
        c.execute(text("CREATE INDEX IF NOT EXISTS idx_audit_created_at ON audit_logs(created_at)"))
        admin_user = os.getenv("INITIAL_ADMIN_USERNAME", "admin")
        admin_pass = os.getenv("INITIAL_ADMIN_PASSWORD")
        if not admin_pass and ENV != "production":
            admin_pass = "admin123"
        if admin_pass:
            exists = c.execute(text("SELECT id FROM users WHERE username=:u"), {"u": admin_user}).first()
            if not exists:
                c.execute(text("INSERT INTO users(username,password_hash,role) VALUES(:u,:p,'admin')"),
                          {"u": admin_user, "p": pwd.hash(admin_pass)})


init_db()


def current_user(request):
    return request.session.get("user")


def csrf_token(request):
    token = request.session.get("csrf_token")
    if not token:
        token = secrets.token_urlsafe(32)
        request.session["csrf_token"] = token
    return token


def check_csrf(request, token):
    return bool(token) and secrets.compare_digest(token, request.session.get("csrf_token", ""))


def redirect_login():
    return RedirectResponse("/login", 303)


def rows(sql="SELECT * FROM records ORDER BY id DESC", params=None):
    with db() as c:
        result = c.execute(text(sql), params or {}).mappings().all()
    return [dict(x) for x in result]


def log_action(request, action, target_type="", target_id="", details=""):
    u = current_user(request) or {}
    with db() as c:
        c.execute(text("""INSERT INTO audit_logs(user_id,username,action,target_type,target_id,details)
                        VALUES(:uid,:un,:a,:tt,:tid,:d)"""),
                  {"uid":u.get("id"), "un":u.get("username"), "a":action,
                   "tt":target_type, "tid":str(target_id) if target_id else "", "d":details})


def stats_for(rs):
    return {"total":len(rs), "used":sum(x.get("status")=="Used" for x in rs),
            "free":sum(x.get("status")=="Free" for x in rs), "reserved":sum(x.get("status")=="Reserved" for x in rs)}


def render_home(request, records=None, edit=None, message=None, error=None, page=1, pages=1):
    if not current_user(request): return redirect_login()
    if records is None:
        per_page = 50
        total = rows("SELECT COUNT(*) AS n FROM records")[0]["n"]
        pages = max(1, (total + per_page - 1)//per_page)
        page = max(1, min(page, pages))
        records = rows("SELECT * FROM records ORDER BY id DESC LIMIT :lim OFFSET :off", {"lim":per_page,"off":(page-1)*per_page})
    # Stats are global, not page-limited.
    all_rs = rows("SELECT status FROM records")
    return templates.TemplateResponse(request=request, name="index.html", context={"request":request,"records":records,"stats":stats_for(all_rs),
        "edit":edit,"message":message,"error":error,"page":page,"pages":pages,"csrf":csrf_token(request)})


@app.get("/health")
def health():
    with db() as c: c.execute(text("SELECT 1"))
    return {"status":"ok"}


@app.get("/login", response_class=HTMLResponse)
def login_page(request:Request):
    if current_user(request): return RedirectResponse("/",303)
    return templates.TemplateResponse(request=request, name="login.html", context={"request":request,"error":None,"csrf":csrf_token(request)})


@app.post("/login", response_class=HTMLResponse)
def login(request:Request, username:str=Form(...), password:str=Form(...), csrf:str=Form("")):
    if not check_csrf(request, csrf):
        return templates.TemplateResponse(request=request, name="login.html", context={"request":request,"error":"Invalid security token. Refresh and try again.","csrf":csrf_token(request)}, status_code=400)
    with db() as c: u=c.execute(text("SELECT * FROM users WHERE username=:u"), {"u":username.strip()}).mappings().first()
    if u and pwd.verify(password, u["password_hash"]):
        request.session["user"]={"id":u["id"],"username":u["username"],"role":u["role"]}
        request.session["csrf_token"] = secrets.token_urlsafe(32)
        log_action(request,"login")
        return RedirectResponse("/",303)
    return templates.TemplateResponse(request=request, name="login.html", context={"request":request,"error":"Invalid username or password.","csrf":csrf_token(request)}, status_code=401)


@app.get("/logout")
def logout(request:Request):
    if current_user(request): log_action(request,"logout")
    request.session.clear(); return RedirectResponse("/login",303)


@app.get("/",response_class=HTMLResponse)
def home(request:Request, page:int=1):
    return render_home(request,page=page)


@app.post("/save")
def save(request:Request, record_id:str=Form(""), province:str=Form("SHIRAZ"), type:str=Form("CORE"),
         source_ne:str=Form(""), source_port:str=Form(""), direction:str=Form("In"), dest_ne:str=Form(""),
         dest_port:str=Form(""), rate_type:str=Form("ODUCN"), rate_number:str=Form("1"), status:str=Form("Free"),
         service:str=Form(""), csrf:str=Form("")):
    u=current_user(request)
    if not u: return redirect_login()
    if not check_csrf(request,csrf): return RedirectResponse("/?error=csrf",303)
    if not all([source_ne.strip(),source_port.strip(),dest_ne.strip(),dest_port.strip()]): return RedirectResponse("/?error=required",303)
    values={"province":province.strip(),"type":type.strip(),"source_ne":source_ne.strip(),"source_port":source_port.strip(),
            "direction":direction.strip(),"dest_ne":dest_ne.strip(),"dest_port":dest_port.strip(),"rate_type":rate_type.strip(),
            "rate_number":str(rate_number).strip(),"status":status.strip(),"service":service.strip() or "N/A"}
    with db() as c:
        if record_id:
            rid=int(record_id)
            values["id"]=rid
            c.execute(text("""UPDATE records SET province=:province,type=:type,source_ne=:source_ne,source_port=:source_port,
                direction=:direction,dest_ne=:dest_ne,dest_port=:dest_port,rate_type=:rate_type,rate_number=:rate_number,
                status=:status,service=:service,updated_at=CURRENT_TIMESTAMP WHERE id=:id"""),values)
            action="update"
        else:
            res=c.execute(text("""INSERT INTO records(province,type,source_ne,source_port,direction,dest_ne,dest_port,rate_type,rate_number,status,service)
                VALUES(:province,:type,:source_ne,:source_port,:direction,:dest_ne,:dest_port,:rate_type,:rate_number,:status,:service)
                RETURNING id"""),values)
            rid=res.scalar_one()
            action="create"
    log_action(request,action,"record",rid)
    return RedirectResponse(f"/?success={'updated' if record_id else 'added'}",303)


@app.get("/edit/{record_id}",response_class=HTMLResponse)
def edit(request:Request,record_id:int):
    if not current_user(request): return redirect_login()
    with db() as c: e=c.execute(text("SELECT * FROM records WHERE id=:id"),{"id":record_id}).mappings().first()
    return render_home(request,edit=dict(e) if e else None,error=None if e else "Record not found.")


@app.post("/delete")
def delete(request:Request, ids:list[int]=Form(...), csrf:str=Form("")):
    u=current_user(request)
    if not u: return redirect_login()
    if u["role"] != "admin": return RedirectResponse("/?error=permission",303)
    if not check_csrf(request,csrf): return RedirectResponse("/?error=csrf",303)
    with db() as c:
        for i in ids: c.execute(text("DELETE FROM records WHERE id=:id"),{"id":i})
    log_action(request,"delete","record",",".join(map(str,ids)))
    return RedirectResponse("/?success=deleted",303)


@app.get("/query",response_class=HTMLResponse)
def query(request:Request,id:str="",province:str="",type:str="",source_ne:str="",source_port:str="",direction:str="",dest_ne:str="",dest_port:str="",rate_type:str="",rate_number:str="",status:str="",service:str=""):
    if not current_user(request): return redirect_login()
    vals={"id":id,"province":province,"type":type,"source_ne":source_ne,"source_port":source_port,"direction":direction,"dest_ne":dest_ne,"dest_port":dest_port,"rate_type":rate_type,"rate_number":rate_number,"status":status,"service":service}
    clauses=[]; params={}
    for k,v in vals.items():
        if v and v!="All":
            if k=="id":
                try: clauses.append("id=:id"); params["id"]=int(v)
                except: clauses.append("1=0")
            else:
                clauses.append(f"LOWER({k}) LIKE LOWER(:{k})"); params[k]="%"+v+"%"
    where=(" WHERE "+" AND ".join(clauses)) if clauses else ""
    rs=rows("SELECT * FROM records"+where+" ORDER BY id DESC",params)
    return render_home(request,records=rs,message=f"Found {len(rs)} record(s)",page=1,pages=1)


@app.post("/import")
async def import_excel(request:Request,file:UploadFile=File(...),csrf:str=Form("")):
    if not current_user(request): return redirect_login()
    if not check_csrf(request,csrf): return RedirectResponse("/?error=csrf",303)
    try:
        data=await file.read()
        if len(data)>10*1024*1024: return RedirectResponse("/?error=file_too_large",303)
        df=pd.read_excel(BytesIO(data))
        mapping={}; aliases={"source ne":"source_ne","source port":"source_port","dest ne":"dest_ne","dest port":"dest_port","rate type":"rate_type","rate number":"rate_number","rate #":"rate_number"}
        for col in df.columns:
            x=str(col).lower().strip().replace("_"," "); mapping[col]=aliases.get(x,x.replace(" ","_"))
        df=df.rename(columns=mapping); n=0
        with db() as c:
            for _,r in df.iterrows():
                def g(k,d=""):
                    v=r.get(k,d); return d if pd.isna(v) else str(v).strip()
                if not g("source_ne") or not g("source_port") or not g("dest_ne") or not g("dest_port"): continue
                rn=g("rate_number","1").split(".")[0]
                c.execute(text("""INSERT INTO records(province,type,source_ne,source_port,direction,dest_ne,dest_port,rate_type,rate_number,status,service)
                    VALUES(:province,:type,:source_ne,:source_port,:direction,:dest_ne,:dest_port,:rate_type,:rate_number,:status,:service)"""),
                    {"province":g("province","SHIRAZ"),"type":g("type","CORE"),"source_ne":g("source_ne"),"source_port":g("source_port"),"direction":g("direction","In"),"dest_ne":g("dest_ne"),"dest_port":g("dest_port"),"rate_type":g("rate_type","ODUCN"),"rate_number":rn,"status":g("status","Free"),"service":g("service","N/A")}); n+=1
        log_action(request,"import","records",details=f"{n} records from {file.filename}")
        return RedirectResponse(f"/?success=imported&n={n}",303)
    except Exception:
        return RedirectResponse("/?error=import",303)


@app.get("/export")
def export_excel(request:Request):
    if not current_user(request): return redirect_login()
    df=pd.DataFrame(rows())
    if df.empty: return RedirectResponse("/?error=no_data",303)
    cols=["id"]+FIELDS
    out=BytesIO()
    with pd.ExcelWriter(out,engine="openpyxl") as w: df[cols].to_excel(w,index=False,sheet_name="Service Records")
    out.seek(0); log_action(request,"export","records",details=f"{len(df)} records")
    return StreamingResponse(out,media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition":f'attachment; filename="service_usage_{datetime.now():%Y%m%d_%H%M%S}.xlsx"'})


@app.get("/profile",response_class=HTMLResponse)
def profile(request:Request):
    if not current_user(request): return redirect_login()
    return templates.TemplateResponse(request=request, name="profile.html", context={"request":request,"user":current_user(request),"error":None,"success":None,"csrf":csrf_token(request)})


@app.post("/profile/password")
def change_password(request:Request,current_password:str=Form(...),new_password:str=Form(...),confirm_password:str=Form(...),csrf:str=Form("")):
    u=current_user(request)
    if not u: return redirect_login()
    if not check_csrf(request,csrf): return RedirectResponse("/profile?error=csrf",303)
    if len(new_password)<10 or new_password!=confirm_password: return RedirectResponse("/profile?error=password",303)
    with db() as c: row=c.execute(text("SELECT password_hash FROM users WHERE id=:id"),{"id":u["id"]}).mappings().first()
    if not row or not pwd.verify(current_password,row["password_hash"]): return RedirectResponse("/profile?error=current",303)
    with db() as c: c.execute(text("UPDATE users SET password_hash=:p WHERE id=:id"),{"p":pwd.hash(new_password),"id":u["id"]})
    log_action(request,"password_change","user",u["id"])
    return RedirectResponse("/profile?success=changed",303)


@app.get("/users",response_class=HTMLResponse)
def users(request:Request):
    u=current_user(request)
    if not u: return redirect_login()
    if u["role"]!="admin": return RedirectResponse("/",303)
    with db() as c: us=[dict(x) for x in c.execute(text("SELECT id,username,role,created_at FROM users ORDER BY id")).mappings().all()]
    return templates.TemplateResponse(request=request, name="users.html", context={"request":request,"users":us,"error":request.query_params.get("error"),"csrf":csrf_token(request)})


@app.post("/users")
def add_user(request:Request,username:str=Form(...),password:str=Form(...),role:str=Form("user"),csrf:str=Form("")):
    u=current_user(request)
    if not u or u["role"]!="admin": return RedirectResponse("/",303)
    if not check_csrf(request,csrf): return RedirectResponse("/users?error=csrf",303)
    if len(password)<10 or role not in ("user","admin"): return RedirectResponse("/users?error=invalid",303)
    try:
        with db() as c: c.execute(text("INSERT INTO users(username,password_hash,role) VALUES(:u,:p,:r)"),{"u":username.strip(),"p":pwd.hash(password),"r":role})
        log_action(request,"create","user",details=username.strip())
    except IntegrityError: return RedirectResponse("/users?error=exists",303)
    return RedirectResponse("/users",303)


@app.post("/users/delete")
def delete_user(request:Request,user_id:int=Form(...),csrf:str=Form("")):
    u=current_user(request)
    if not u or u["role"]!="admin": return RedirectResponse("/",303)
    if user_id==u["id"] or not check_csrf(request,csrf): return RedirectResponse("/users?error=not_allowed",303)
    with db() as c: c.execute(text("DELETE FROM users WHERE id=:id"),{"id":user_id})
    log_action(request,"delete","user",user_id)
    return RedirectResponse("/users",303)
